///////////////////////////////////////////////////////////////////////////////
//  GRADLE CONFIGURATION
///////////////////////////////////////////////////////////////////////////////
plugins {
    java
    id("com.diffplug.spotless") version "6.25.0"
}
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        classpath("org.eclipse.keyple:keyple-gradle:0.2.+") { isChanging = true }
    }
}
apply(plugin = "org.eclipse.keyple")

///////////////////////////////////////////////////////////////////////////////
//  APP CONFIGURATION
///////////////////////////////////////////////////////////////////////////////
repositories {
    mavenLocal()
    mavenCentral()
    maven(url = "https://oss.sonatype.org/content/repositories/snapshots")
}
dependencies {
// Begin Keyple configuration (generated by 'https://keyple.org/components/overview/configuration-wizard/')
    testImplementation("org.eclipse.keypop:keypop-reader-java-api:2.0.1")
    testImplementation("org.eclipse.keypop:keypop-calypso-card-java-api:2.1.0")
    testImplementation("org.eclipse.keypop:keypop-calypso-crypto-legacysam-java-api:0.5.0")
    testImplementation("org.eclipse.keyple:keyple-common-java-api:2.0.1")
    testImplementation("org.eclipse.keyple:keyple-util-java-lib:2.4.0")
    testImplementation("org.eclipse.keyple:keyple-service-java-lib:3.2.1")
    testImplementation("org.eclipse.keyple:keyple-service-resource-java-lib:3.0.1")
    testImplementation("org.eclipse.keyple:keyple-distributed-network-java-lib:2.3.1")
    testImplementation("org.eclipse.keyple:keyple-distributed-local-java-lib:2.3.1")
    testImplementation("org.eclipse.keyple:keyple-distributed-remote-java-lib:2.3.1")
    testImplementation("org.eclipse.keyple:keyple-card-generic-java-lib:3.0.1")
    testImplementation("org.eclipse.keyple:keyple-card-calypso-java-lib:3.1.1")
    testImplementation("org.eclipse.keyple:keyple-card-calypso-crypto-legacysam-java-lib:0.6.0")
    testImplementation("org.eclipse.keyple:keyple-plugin-cardresource-java-lib:2.0.1")
    testImplementation("org.eclipse.keyple:keyple-plugin-stub-java-lib:2.2.1")
// End Keyple configuration

    testImplementation("com.google.code.gson:gson:2.10.1")
    testImplementation("org.slf4j:slf4j-api:2.0.5")
    testImplementation("org.slf4j:slf4j-simple:2.0.5")
    testImplementation(platform("org.junit:junit-bom:5.10.2"))
    testImplementation("org.junit.jupiter:junit-jupiter")
    testImplementation("org.junit.vintage:junit-vintage-engine")
    testImplementation("org.assertj:assertj-core:3.25.3")
    testImplementation("org.mockito:mockito-core:5.11.0")
    testImplementation("org.awaitility:awaitility:4.2.1")
    testImplementation("com.fasterxml.jackson.core:jackson-databind:2.17.0")
}

val javaSourceLevel: String by project
val javaTargetLevel: String by project
java {
    sourceCompatibility = JavaVersion.toVersion(javaSourceLevel)
    targetCompatibility = JavaVersion.toVersion(javaTargetLevel)
    println("Compiling Java $sourceCompatibility to Java $targetCompatibility.")
}

///////////////////////////////////////////////////////////////////////////////
//  TASKS CONFIGURATION
///////////////////////////////////////////////////////////////////////////////
tasks {
    spotless {
        java {
            target("src/**/*.java")
            licenseHeaderFile("${project.rootDir}/LICENSE_HEADER")
            importOrder("java", "javax", "org", "com", "")
            removeUnusedImports()
            googleJavaFormat()
        }
    }
    test {
        testLogging {
            events("passed", "skipped", "failed")
        }
    }
}
